getdoctor(general_physician,amarpreet_singh_riar).
getdoctor(general_physician,sharad_shrivastava).
getdoctor(homoeopath,mansi_arya).
getdoctor(homoeopath,sunil_kumar_dwivedi).
getdoctor(ear_nose_throat_specialist,manish_munjal).
getdoctor(ear_nose_throat_specialist,ajay_jain).
getdoctor(ayurveda,sudha_asokan).
getdoctor(ayurveda,mahesh_shah).
getdoctor(dermatologist,kashyap).
getdoctor(dermatologist,nipun_jain).
getdoctor(gynecologist,gayatri_bala_juneja).

getdiseasedescription(drug_reaction,0).
getdiseasedescription(malaria,1).
getdiseasedescription(allergy,2).
getdiseasedescription(hypothyroidism,3).
getdiseasedescription(psoriasis,4).
getdiseasedescription(gerd,5).
getdiseasedescription(chronic_cholestasis,6).
getdiseasedescription(hepatitis_a,7).
getdiseasedescription(osteoarthristis,8).
getdiseasedescription(vertigo,9).
getdiseasedescription(hypoglycemia,10).
getdiseasedescription(acne,11).
getdiseasedescription(diabetes,12).
getdiseasedescription(impetigo,13).
getdiseasedescription(hypertension,14).
getdiseasedescription(peptic_ulcer_diseae,15).
getdiseasedescription(piles,16).
getdiseasedescription(common_cold,17).
getdiseasedescription(chicken_pox,18).
getdiseasedescription(cervical_spondylosis,19).
getdiseasedescription(hyperthyroidism,20).
getdiseasedescription(urinary_tract_infection,21).
getdiseasedescription(varicose_veins,22).
getdiseasedescription(aids,23).
getdiseasedescription(paralysis_,24).
getdiseasedescription(typhoid,25).
getdiseasedescription(hepatitis_b,26).
getdiseasedescription(fungal_infection,27).
getdiseasedescription(hepatitis_c,28).
getdiseasedescription(migraine,29).
getdiseasedescription(bronchial_asthma,30).
getdiseasedescription(alcoholic_hepatitis,31).
getdiseasedescription(jaundice,32).
getdiseasedescription(hepatitis_e,33).
getdiseasedescription(dengue,34).
getdiseasedescription(hepatitis_d,35).
getdiseasedescription(heart_attack,36).
getdiseasedescription(pneumonia,37).
getdiseasedescription(arthritis,38).
getdiseasedescription(gastroenteritis,39).
getdiseasedescription(tuberculosis,40).

getdiseasesymptoms(dischromic_patches,itching,nodal_skin_eruptions,skin_rash,fungal_infection).
getdiseasesymptoms(chills,continuous_sneezing,shivering,watering_from_eyes,allergy).
getdiseasesymptoms(acidity,chest_pain,cough,stomach_pain,ulcers_on_tongue,vomiting,gerd).
getdiseasesymptoms(abdominal_pain,itching,vomiting,yellowing_of_eyes,chronic_cholestasis).
getdiseasesymptoms(itching,skin_rash,spotting_urination,stomach_pain,drug_reaction).
getdiseasesymptoms(abdominal_pain,internal_itching,loss_of_appetite,vomiting,peptic_ulcer_diseae).
getdiseasesymptoms(extra_marital_contacts,high_fever,muscle_wasting,patches_in_throat,aids).
getdiseasesymptoms(blurred_and_distorted_vision,excessive_hunger,obesity,weight_loss,diabetes).
getdiseasesymptoms(dehydration,diarrhoea,sunken_eyes,vomiting,gastroenteritis).



